In [2]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np 

In [48]:
a = np.array([1,46,695,245,645,134,24,5.43,0])
a

array([  1.  ,  46.  , 695.  , 245.  , 645.  , 134.  ,  24.  ,   5.43,
         0.  ])

In [17]:
type(a)

numpy.ndarray

In [18]:
a.dtype

dtype('float64')

In [19]:
b = ( 2,98,865,321)
np.array(b)

array([  2,  98, 865, 321])

In [20]:
a.ndim

1

In [21]:
a.size

8

In [22]:
a.shape

(8,)

In [25]:
a[7] = 0

In [26]:
a

array([  1.,  46., 695., 245., 645., 134.,  24.,   0.])

### Multi-Dimentional Array

In [41]:
matrix = [[[1,2,3,8], [4,5,6,7]],[[10,20,30,7], [40,50,60,7]],[[10,20,30,7], [40,50,60,7]]]
matrix

[[[1, 2, 3, 8], [4, 5, 6, 7]],
 [[10, 20, 30, 7], [40, 50, 60, 7]],
 [[10, 20, 30, 7], [40, 50, 60, 7]]]

In [42]:
np_matrix = np.array(matrix)
np_matrix


array([[[ 1,  2,  3,  8],
        [ 4,  5,  6,  7]],

       [[10, 20, 30,  7],
        [40, 50, 60,  7]],

       [[10, 20, 30,  7],
        [40, 50, 60,  7]]])

In [43]:
print(np_matrix.size,'\n',np_matrix.ndim,'\n',np_matrix.shape)

24 
 3 
 (3, 2, 4)


#### Reshape

In [49]:
a

array([  1.  ,  46.  , 695.  , 245.  , 645.  , 134.  ,  24.  ,   5.43,
         0.  ])

In [50]:
a.reshape(4,2) # reshape(rows, column) rows*column = total size of original array 

ValueError: cannot reshape array of size 9 into shape (4,2)

In [52]:
a.reshape(3,3,1) # (block, rows, column)

array([[[  1.  ],
        [ 46.  ],
        [695.  ]],

       [[245.  ],
        [645.  ],
        [134.  ]],

       [[ 24.  ],
        [  5.43],
        [  0.  ]]])

In [57]:
np_matrix

array([[[ 1,  2,  3,  8],
        [ 4,  5,  6,  7]],

       [[10, 20, 30,  7],
        [40, 50, 60,  7]],

       [[10, 20, 30,  7],
        [40, 50, 60,  7]]])

In [56]:
np_matrix.reshape(24)

array([ 1,  2,  3,  8,  4,  5,  6,  7, 10, 20, 30,  7, 40, 50, 60,  7, 10,
       20, 30,  7, 40, 50, 60,  7])

In [63]:
np_matrix.reshape(3,-1)

array([[ 1,  2,  3,  8,  4,  5,  6,  7],
       [10, 20, 30,  7, 40, 50, 60,  7],
       [10, 20, 30,  7, 40, 50, 60,  7]])

range(0, 10)

#### Arange

In [66]:
np.arange(15) # in will exclude the end element 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [70]:
np.arange(100,20,-2) # ( start def = 0 , end def = end of that array, jump/step size def = 1  )

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22])

#### Zeros and ones 

In [71]:
np.zeros(4)

array([0., 0., 0., 0.])

In [75]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [79]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

LINSPACE

In [ ]:
np.linspace(0,100,5) # (start, end , how many equal space you want default = 50  )

array([  0.,  25.,  50.,  75., 100.])

In [83]:
np.linspace(0,20, 100,retstep=True)

(array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
         1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
         2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
         3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
         4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
         5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
         6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
         7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
         8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
         9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
        10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
        11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
        12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
        13.13131313, 13.33333333, 13.53535354, 13.7

EYE

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

Brodcasting an Array

In [87]:
three = np.ones((4,3))

In [90]:
three = three*4 
three


array([[16., 16., 16.],
       [16., 16., 16.],
       [16., 16., 16.],
       [16., 16., 16.]])

In [91]:
three[2,2] = 0
three

array([[16., 16., 16.],
       [16., 16., 16.],
       [16., 16.,  0.],
       [16., 16., 16.]])

Copy Fuction

In [92]:
a

array([  1.  ,  46.  , 695.  , 245.  , 645.  , 134.  ,  24.  ,   5.43,
         0.  ])

In [96]:
b = a # shaloow copy just new pointer not a separate memory location 
print(b)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]


In [94]:
a[0] = 100
print(a)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]


In [95]:
print(b)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]


In [ ]:
c = b.copy() # deep copy Creates a separate Memory Location
print(b)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]


In [99]:
print(c)
b[1]= -9999
print(b)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]
[ 1.000e+02 -9.999e+03  6.950e+02  2.450e+02  6.450e+02  1.340e+02
  2.400e+01  5.430e+00  0.000e+00]


In [102]:
b[2]

np.float64(695.0)

In [100]:
print(c)

[100.    46.   695.   245.   645.   134.    24.     5.43   0.  ]


MIN, MAX , ARGMIN, ARGMAX

In [106]:
b.min()

np.float64(-9999.0)

In [107]:
b.argmin()

np.int64(1)

In [108]:
b.max()

np.float64(695.0)

In [110]:
b.argmax()

np.int64(2)